version: "3.7"

services:    
    app:
        build:
            context: .
            dockerfile: Dockerfile        
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - networks-ramon

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "9999:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - networks-ramon

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - networks-ramon
   
    # redis
    redis:
        image: redis:latest
        networks:
            - networks-ramon

networks:
    networks-ramon:
        driver: bridge
